### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by vinta**
- fix TypeError for json.loads in Python 3
- claim Python 3 support in setup.py

### CODE REVIEW

**Comment by galuszkak** [comment]
Looks awesome @vinta ! Can someone merged that @tzangms ?

**Comment by tzangms** [comment]
Merged, I will update package on PyPI tomorrow

**Comment by galuszkak** [comment]
@tzangms before maybe it's good to add django 1.8 support? (in req there is  ``` "django >= 1.4, < 1.7",``` )

**Comment by tzangms** [comment]
oh, I think I should have to setup a project for easier testing, maybe django 1.8 support in next release.

**Comment by galuszkak** [comment]
@tzangms I can setup tox + travis for different python and django versions. If that will be useful I can do it today.

**Comment by tzangms** [comment]
I think I've already have a Mock of elastic transcoder's, maybe modify the `.travis.yml` to run the build will solve the problem? 

I don't have experience on tox :p

**Pull request merged**
